import re


def ask_repository(question: str, context: str) -> str:
    """
    Local repository Q&A fallback.
    Works without Gemini API.
    """

    question_lower = question.lower()

    # ---------------------------------------------
    # Find function questions
    # ---------------------------------------------

    if (
        "where" in question_lower
        and (
            "function" in question_lower
            or "method" in question_lower
        )
    ):

        functions = re.findall(
            r"FILE:\s*(.*?)\n.*?FUNCTIONS:\s*(.*?)(?:\n|$)",
            context,
            re.DOTALL
        )

        for file_name, function_names in functions:

            if function_names.strip():

                return (
                    f"The function **{function_names.strip()}** "
                    f"is located in **{file_name.strip()}**."
                )

    # ---------------------------------------------
    # What does function do?
    # ---------------------------------------------

    if (
        "what does" in question_lower
        or "what is" in question_lower
        or "explain" in question_lower
    ):

        match = re.search(
            r"def\s+(\w+)\s*\([^)]*\):\s*(.*?)(?=\n\s*def\s|\Z)",
            context,
            re.DOTALL
        )

        if match:

            function_name = match.group(1)
            function_body = match.group(2).strip()

            return (
                f"The function **{function_name}()** is defined "
                f"in the retrieved repository code.\n\n"
                f"It performs the following operation:\n"
                f"```python\n{function_body}\n```"
            )

    # ---------------------------------------------
    # Security questions
    # ---------------------------------------------

    security_keywords = [
        "security",
        "vulnerability",
        "unsafe",
        "dangerous",
        "eval",
        "exec"
    ]

    if any(
        keyword in question_lower
        for keyword in security_keywords
    ):

        dangerous_functions = re.findall(
            r"\b(eval|exec)\s*\(",
            context
        )

        if dangerous_functions:

            return (
                "⚠️ A potential security issue was found.\n\n"
                f"The repository uses: "
                f"**{', '.join(set(dangerous_functions))}()**.\n\n"
                "These functions can execute dynamically "
                "provided Python code and should be used "
                "very carefully with untrusted input."
            )

        return (
            "No obvious `eval()` or `exec()` usage was found "
            "in the retrieved repository context."
        )

    # ---------------------------------------------
    # Generic repository answer
    # ---------------------------------------------

    return (
        "🔍 I found the following relevant repository code:\n\n"
        f"```text\n{context}\n```\n\n"
        "This answer was generated by CodeGuardian AI's "
        "local RAG fallback because the Gemini API quota "
        "is currently unavailable."
    )